name: Package

on: workflow_dispatch

jobs:
  package_windows:
    name: 编译Win平台
    runs-on: windows-2019

    strategy:
      matrix:
        include:
          - win_ver: x86版
            msvc_arch: x86
            libsodium_arch: Win32
            
          - win_ver: x64版
            msvc_arch: x64
            libsodium_arch: x64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install libsodium
        shell: bash
        run: |
          curl -LO https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-msvc.zip
          unzip libsodium-1.0.18-stable-msvc.zip

      - name: Configure
        shell: bash
        working-directory: ./LANDrop
        run: |
          echo "INCLUDEPATH += ../libsodium/include" >> LANDrop.pro
          echo "LIBS += -L../libsodium/${{ matrix.libsodium_arch }}/Release/v142/dynamic -llibsodium" >> LANDrop.pro

      - name: Build
        shell: cmd
        working-directory: ./LANDrop
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          qmake -tp vc
          msbuild -m -p:Configuration=Release .

      - name: Package
        shell: bash
        working-directory: ./LANDrop
        run: |
          mkdir LANDrop
          cd LANDrop
          mv ../release/LANDrop.exe .
          windeployqt LANDrop.exe
          cp ../../libsodium/${{ matrix.libsodium_arch }}/Release/v142/dynamic/libsodium.dll .
          # curl -LO https://aka.ms/vs/16/release/vc_redist.x64.exe

      - name: Zip
        working-directory: ./LANDrop
        run: Compress-Archive LANDrop LANDrop-win-${{ matrix.msvc_arch }}.zip

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows-Build
          path: LANDrop/LANDrop-win-${{ matrix.msvc_arch }}.zip
